### ISSUE TITLE
The weather icons aren't properly displayed  on the web component

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-weather-forecast#5]
As you can see from the screenshot below, the weather web components doesn't show the icons.

# Weather in South Tyrol
https://webcomponents.opendatahub.com/webcomponent/weather-in-south-tyrol
![Schermata da 2023-08-02 17-49-36](https://github.com/noi-techpark/webcomp-weather-forecast/assets/7909989/29781007-5097-4043-8540-c441ad6a2250)

# Weather in South Tyrol - forecast
https://webcomponents.opendatahub.com/webcomponent/weather-in-south-tyrol-forecast
![Schermata da 2023-08-02 17-49-27](https://github.com/noi-techpark/webcomp-weather-forecast/assets/7909989/64ca17d8-e354-4131-98ff-80946ae9842e)

# Weather in South Tyrol - mountain weather
https://webcomponents.opendatahub.com/webcomponent/weather-in-south-tyrol-mountain-weather
![Schermata da 2023-08-02 17-52-48](https://github.com/noi-techpark/webcomp-weather-forecast/assets/7909989/86908ea8-c419-457d-abd4-4f1c164ad107)

# Problem description
Due to the release of the new Marketplace, the link to the svg file of the icon is changed.

# Possible solutions are
- get the svgs from IDM and add it to the webcomponent;
- get this svgs and host it on another url (Open data Hub url);
- use the new svgs from marketplace
- use the svgs from marketplace provided by SIAG as suedtirol.info does

During an internal discussion, it emerged that the most likely solution is to get the icons from SIAG.

**Comment by RudiThoeni** [comment]
Hi Stefano

I changed the icons to use Siag icons for all 3 webcomponents.
Also the main webcomponent did not work because of a deprecated (removed from chrome) js code which is now also fixed
cheers
Rudi

**Comment by sseppi** [comment]
Hi Rudi!

Thi is super! Thank you!
Have you published the web component in testing or is it already on production?

Best
Stefano

**Comment by RudiThoeni** [comment]
Yes they are already on test & production

**Comment by sseppi** [comment]
Super! So we can move the issue in the done lane!
